export const InsightConstant = Object.freeze({
    LIGHT_LOGO: '../app/assets/images/insight-patch/lights.png',
    POOL_LOGO: '../app/assets/images/insight-patch/pools-icon.png',
    IRRIGATION_LOGO: '../app/assets/images/insight-patch/Irrigation-icon.png',
    REF_ICON: '../app/assets/images/insight-patch/refrsh-icon.png',
    MORE_ICON: '../app/assets/images/insight-patch/more-icon.png',
    LIGHT_HEADING: 'Lights',
    POOL_HEADING: 'Pool',
    IRRIGATION_HEADING: 'Irrigation',
    LIGHTS_IND: 'Light Controllers Installed',
    POOL_OW: 'Pool Overview',
    IRRIGATION_MON: 'Irrigation Valves Monitored',
    LAST_UPDT:'Last Updated',
    STATUS:'Status',
    CHEM_LVL:'Chemical Levels',
    TEMP:'Temperature',
    MAN_CLSD:'Manually Closed',
    LAST_REP:'Last Reported',
    CURR_MNTH: 'Current Month',
    LAST_MNTH: 'Last Month',
    TOD: 'Total to Date',
    APD: 'AVR. Per Day',
    TOM: 'Total to Month',
});

